services:
  - type: web
    name: intellectualos
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /online
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
